### ISSUE TITLE
Qt 6 update?

### ISSUE THREAD

**Issue by enkeyz** [PapirusDevelopmentTeam/arc-kde#133]
Can we expect a Qt 6 upgrade? Arc KDE broke after qBittorrent started using Qt 6.

**Comment by varlesh** [comment]
I'm not tested Qt 6 apps... But i thing it's possible use:
https://github.com/tsujan/Kvantum/discussions/596

**Comment by tsujan** [comment]
I was lead here by chance — by following some links.

Kvantum was ported to Qt6 a long time ago — its Arch package already provides both Qt5 and Qt6 style plugins. The default compilation is still against Qt5, but that will change when Qt6 becomes the default version in rolling distros (like Arch).

You still need a Qt6 platform plugin to activate it for Qt6 apps. LXQt already has it in its git Qt6 branches, but `qt6ct` should work too. However, don't forget that you'll need to deactivate `qt6ct` as soon as KDE/LXQt is completely ported to Qt6 (soon) if you use one of those DEs.

Anyway, no Kvantum theme needs any change in order to work with Qt6. So, this can be closed.

**Comment by SmartFinn** [comment]
`qt6-style-kvantum` package added to [`ppa:papirus/papirus`](https://launchpad.net/~papirus/+archive/ubuntu/papirus) for Ubuntu 22.04 (not sure that working, because `qt6ct` package is missing), Ubuntu 23.04, and Ubuntu 23.10.

**Comment by groeffen** [comment]
Thanks @SmartFinn for your persistent dedication to this project - As an long time Materia-lover: Thank you!
