### ISSUE TITLE
Arc KDE in the AUR

### ISSUE THREAD

**Issue by mustaqimM** [PapirusDevelopmentTeam/arc-kde#6]
Has Arc KDE been removed from the AUR?

**Comment by SmartFinn** [comment]
Arc KDE don't has any official packages. But you can use this https://aur.archlinux.org/packages/arc-kde-git/

**Comment by N-kay** [comment]
At least `arc-dark-suite` and `arc-icon-theme` are completely removed from the AUR. Maybe more.
I was hoping to find some kind of explanation, but I guess I won't find it here, understanadbly.

The `arc-kde-git` package is kinda new, let's hope this one stays.

**Comment by bilelmoussaoui** [comment]
@N-kay i was the packager of arc-icon-theme on AUR and i was contacted in order to remove the package so they can provide it in the official repository. and i did accept ;) as it's much more easier to install than having to build it all by yourself ;) you still can use arc-icon-theme-git if you want to modify things on the pkgbuild file
