### ISSUE TITLE
Provide arc darker colors

### ISSUE THREAD

**Issue by memeplex** [PapirusDevelopmentTeam/arc-kde#94]
There is a kvantum theme but no color scheme. Also, when I preview the darker kvantum theme the kvantum window turns white as in the light variant.

**Comment by varlesh** [comment]
Screenshot on README - it's Arc Darker
For Darker use:
- **Kvantum** theme **Arc Darker**
- **Aurorae Arc Dark**
- **Colorscheme Arc Light**
- **Plasma** theme **Arc Dark**
Darker - it's only dark toolbar and window decoration. Left sidebar impossible set dark, because window widget not support that - it's single area
